name: bangsatnyacintapertama_graphql_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  gql_http_link: ^1.0.1
  graphql_flutter: ^5.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  flutter_gen: ^5.2.0
  graphql_codegen: ^0.13.5

flutter:
  generate: true